version: "3"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
    container_name: mysql

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"